### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hhkaos** [hhkaos/youtube-video-tour#1]
* [ ] Migrate to JS 3.21 to support vector tiles
* [ ] Improve messaging when something fails
* [ ] Improve integration with Rollbar
